- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
      files: \.sh
    - id: check-json
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/prettier/prettier
  rev: 2.1.1
  hooks:
    - id: prettier
      name: Format app with prettier
